### PR TITLE
Tcp mode

### PR DESCRIPTION
**Pull request by till**
This turned out to be a lot more work than expected, I tried to break it up into meaningful commits for you.

# Features/Updates

 - added the ability for `mode tcp`
 - added a test suite to assert on the configuration parsing
 - added a `Makefile` with `test` and `build` targets

# Fixes

 - I changed that in swarm mode, you need to inspect services (vs containers)
 - I sent HAProxy logs to `stdout` (so you see that's going on via `docker [service] logs`)

# Refactoring

 - I refactored your Python class heavily and tried to push all "label" work into a dedicated helper class
 - I moved your scripts around (and updated the `Dockerfile`)

# LBNL

If you add a Travis-CI in another PR, let me know and I'll rebase on it so we can see if it all works. But the basics for now are `make test` or `pytests -s tests/`. I would also add a full integration test where we start a container or stack and assert on a few things via HAProxy stats page.

### CODE REVIEW

**Comment by byjg** [comment]
I created the .travis Job right after you opened the PR. Could you push something to your branch in order to trigger a .travis build?

**Comment by till** [comment]
It seems to trigger them. No idea why Travis-CI doesn't show up here. 🤷‍♂️

**Comment by till** [comment]
And they seem to complete! :) 
https://travis-ci.org/github/byjg/docker-easy-haproxy/builds/695066932

**Comment by till** [comment]
I should add, I am not entirely sure about my "Python", it's to the best of my abilities. But I usually don't use it much, aside from Ansible. If you have any suggestions or require fixes, let me know.

**Comment by byjg** [comment]
Github is not showing the job here probably because the Job was created after the PR. 

Anyway, it worked !!! 👏 

I'll take a look until the end of the day, and if I dont have any comments merge it :)

**Comment by byjg** [comment]
I tested your PR and I found a small bug in the SSL part. I worked locally and fixed the issue. I changed a little the unit tests. 

I'll merge your PR, and apply my changes in the branch 2.2.

**Comment by byjg** [comment]
I created the docker image `byjg/easy-haproxy:2.2.0-rc4` . I'll leave running for a week and after that I'll merge into master and create a new docker tag.

**Pull request merged**
